const { v4: uuid } = require('uuid');

/**
 * Class representing a User model
 */
class User {
  /**
   *
   * @param {string} id - user id, generated by uuid v4 by default
   * @param {string} name - user name
   * @param {string} login - user login
   * @param {string} password - user password
   */
  constructor({
    id = uuid(),
    name = 'USER',
    login = 'user',
    password = 'P@55w0rd'
  } = {}) {
    this.id = id;
    this.name = name;
    this.login = login;
    this.password = password;
  }

  /**
   * Convert user object into new object with no user password
   * @param {Object} user - user object
   * @returns {{name, id, login}} - new object with no user password
   */
  static toResponse(user) {
    const { id, name, login } = user;
    return { id, name, login };
  }
}

module.exports = User;
