version: "3.9"
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
    - ./logs:/usr/src/app/logs
    - ./src:/usr/src/app/src
    environment:
      PORT: ${PORT}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    networks:
      - net
  postgres:
    build: ./database
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
    - ./db_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - net
networks:
  net:
    driver: bridge
