const { v4: uuid } = require('uuid');

/**
 * Class representing a Board model
 */
class Board {

  /**
   *
   * @param {string} id - user id, generated by uuid v4 by default
   * @param {string} title - board title
   * @param {Object[]} columns - columns bound to board
   */
  constructor({
    id = uuid(),
    title = 'Autotest board',
    columns = [
      {
        id: uuid(),
        title: 'Backlog',
        order: 0
      }
    ]
  } = {}) {
    this.id = id;
    this.title = title;
    this.columns = columns;
  }
}

module.exports = Board;
